
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/bbom
    username: bbom
    password: bbom
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

